---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
  - Safari
  - Mail
  - Maps
  - Photos
  - Calendar
  - Contacts
  - Reminders
  - Freeform
  - TV
  - Music
  - News

dockitems_persist:
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5
  - name: "Slack"
    path: "/Applications/Slack.app"
    pos: 2
  - name: "Chrome"
    path: "/Applications/Google Chrome.app"
    pos: 3
  - name: "iterm2"
    path: "/Applications/iTerm.app"
    pos: 4
  - name: "VS Code"
    path: "/Applications/Visual Studio Code.app"
    pos: 5
  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app/"
    pos: 6
  - name: "Docker Desktop"
    path: "/Applications/Docker.app"
    pos: 7
  - name: "GitKraken"
    path: "/Applications/GitKraken.app"
    pos: 8
  - name: "Notion"
    path: "/Applications/Notion.app"
    pos: 9

configure_sudoers: true
# sudoers_custom_config: ''
# Example:
sudoers_custom_config: '%admin ALL=(ALL) NOPASSWD: ALL'
# Allow users in admin group to use sudo with no password.
  # %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  # - autoconf
  # - bash-completion
  # - gettext
  # - gifsicle
  # - gh
  # - go
  # - gpg
  # - httpie
  # - libevent
  # - sqlite
  # - mcrypt
  # - node
  # - nvm
  # - php
  # - openssl
  # - pv
  # - wget
  # - wrk
  - coreutils
  - cowsay
  - doxygen
  - git
  - iperf
  - mas
  - nmap
  - readline
  - ssh-copy-id
  - vim
  - zsh
  - zsh-history-substring-search

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - chromedriver
  # - dropbox
  # - handbrake
  # - licecap
  # - sequel-ace
  # - sublime-text
  # - transmit
  - docker
  - firefox
  - front
  - gitkraken
  - google-chrome
  - google-drive
  - iterm2
  - lastpass
  - microsoft-office
  - microsoft-remote-desktop
  - notion
  - slack
  - visual-studio-code
  - hpedrorodrigues/tools/dockutil


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
  # - { id: 1298450641, name: "monday.com (1.0.27)" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
